dayanik/dayanik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views


urlpatterns = [
    # flatpages - статичные страницы
    path('about/', include('django.contrib.flatpages.urls')),
    path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
    path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
    # adminka
    path('admin/', admin.site.urls),
    # регистрация и авторизация
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    # posts
    path('', include('posts.urls'))
]

dayanik/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='index'),
    path('<int:pk>/', views.PostView.as_view(), name='post'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('', views.dayanik, name='dayanik')
]

dayanik/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.InlogView.as_view(), name='login'),
    path('password_change/', views.PwdChangeView.as_view(),
          name='password_change'),
    path('password_reset/', views.PwdResetView.as_view(),
          name='password_reset'),
    path(
        'reset/<uidb64>/<token>/',
        views.PwdResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
]

dayanik/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True,
                                null=True, related_name='posts',
                                verbose_name='Пост')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'
        ordering = ['-pub_date']
    

dayanik/users/models.py
from django.db import models

# Create your models here.

dayanik/posts/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']
    
    def __init__(self, *args, **kwargs) -> None:
        super(PostForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label

dayanik/users/forms.py
from django.contrib.auth import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')
    
    def __init__(self, *args, **kwargs) -> None:
        super(CreationForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label


class AuthForm(forms.AuthenticationForm):
    def __init__(self, *args, **kwargs) -> None:
        super(AuthForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label


class PwdChangeForm(forms.PasswordChangeForm):
    def __init__(self, *args, **kwargs) -> None:
        super(PwdChangeForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label


class PwdResetForm(forms.PasswordResetForm):
    def __init__(self, *args, **kwargs) -> None:
        super(PwdResetForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label


class PwdResetConfirmForm(forms.PasswordResetForm):
    def __init__(self, *args, **kwargs) -> None:
        super(PwdResetConfirmForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label

dayanik/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView

from .models import Post
from .forms import PostForm


User = get_user_model()


def dayanik(request):
    return render(request, 'dayanik.html', {})


class BlogView(ListView):
    template_name = 'index.html'
    context_object_name = 'posts'
    queryset = Post.objects.all()


class PostView(DetailView):
    template_name = 'post.html'
    context_object_name = 'post'
    model = Post


class PostUpdateView(UpdateView):
    template_name = 'post_edit.html'
    model = Post
    fields = ['title', 'text']
    success_url = reverse_lazy('posts:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_object_or_404(Post, pk=self.kwargs['pk']).author
        return context


class ProfileView(DetailView, LoginRequiredMixin, CreateView):
    template_name = 'profile.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:index')

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        context['profile'] = profile
        context['posts'] = Post.objects.filter(author=profile).all()
        return context
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


'''
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'text']
    success_url = reverse_lazy('posts:index')
    template_name = 'new_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
'''

dayanik/users/views.py
from django.views.generic import CreateView
from django.contrib.auth import views
from django.urls import reverse_lazy
from . import forms
from django.shortcuts import redirect


class SignUp(CreateView):
    form_class = forms.CreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class InlogView(views.LoginView):
    form_class = forms.AuthForm


class PwdChangeView(views.PasswordChangeView):
    form_class = forms.PwdChangeForm


class PwdResetView(views.PasswordResetView):
    form_class = forms.PwdResetForm


class PwdResetConfirmView(views.PasswordResetConfirmView):
    form_class = forms.PwdResetForm

dayanik/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block description %}<meta name="description" content="Описание сайта в снипете">{% endblock %}
        <title>{% block title %}Блог{% endblock %}</title>
        {% load static %}
        <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
    <div class="wrapper">
        <header class="header">
            {% include 'nav.html' %}
        </header>
        <section class="main">
            {% block content %}
            {% endblock %}
        </section>
        <aside class="aside aside-1"></aside>
        <aside class="aside aside-2"></aside>
        <footer class="footer">
            {% include 'footer.html' %}
        </footer>
    </div>
    </body>
</html>

dayanik/templates/dayanik.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Dayanik.ru{% endblock %}</title>
        {% load static %}
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'dayanik.css' %}">
    </head>
    <body>
    <div class="wrapper">
        <header>
            <h1>Привет! Я Даян Исхаков.</h1>
            <h2>Я бэкенд-разработчик</h2>
        </header>
        <section>
            <article>
                <h3>Мой стэк:</h3>
                <ul>
                    <li>Pyhton</li>
                    <li>Git GitHub</li>
                    <li>Django DRF</li>
                    <li>Html5 Css3</li>
                    <li>Git GitHub</li>
                    <li>Linux Bash</li>
                    <li>Pip Virtualenv</li>
                    <li>Pycharm VSCode</li>
                    <ul>
                        <li><b><i>Планируется</i></b></li>
                        <li>Mysql PostgreSQL SQlite3</li>
                        <li>Redis</li>
                        <li>Celery</li>
                        <li>jquery js</li>
                        <li>FastApi</li>
                        <li>Docker</li>
                    </ul>
                </ul>
            </article>
            <article>
                <h3>Мой опыт:</h3>
                <ul>
                    <li>Снэма</li>
                    <li>Фриланс</li>
                </ul>
            </article>
            <article>
                <h3>Мои проекты:</h3>
                <ul>
                    <li>Dayanik.ru</li>
                </ul>
            </article>
            <article>
                <h3>Моё образование:</h3>
                <ul>
                    <li>Башгу, бакалавр "Электроника и наноэлектроника"</li>
                    <li>Курс Stepik "Поколение Python"</li>
                </ul>
            </article>
            <article>
                <h3>Мои увлечения:</h3>
                <ul>
                    <li>Футбол футзал</li>
                    <li>Рок-музыка</li>
                    <li>Чтение книг</li>
                    <li>Игра на гитаре</li>
                    <li>Путешествие на машине</li>
                </ul>
            </article>
            <article>
                <h3>Мои планы:</h3>
                <ul>
                    <li>Senior разработчик +100500k зп</li>
                    <li>Собственный бизнес</li>
                    <li>Устроиться в FAANG</li>
                    <li>Куча детей</li>
                    <li>К пенсии переселиться на марс</li>
                </ul>
            </article>
        </section>
        
        <footer>
            <a href="{% url 'posts:dayanik' %}">Dayanik</a>
            <a href="{% url 'posts:index' %}">Блог</a>
            <a href="https://github.com/Dayad1994" target="_blank">GitHub</a>
        </footer>
    </div>
    </body>
</html>

dayanik/templates/footer.html
<a href="/about/about-author/">Об авторе</a>
<a href="/about/about-spec/">Технологии</a>
<a href="/about-us/">О нас</a>
<a href="/terms/">Условия использования</a>
<a href="/about/contacts/">Контакты</a>

dayanik/templates/form.html
{% extends 'base.html' %}
{% block title %}Титулка{% endblock %}
{% block content %}
{% if '/reset/' in request.path and not validlink %}
    <article class="article">
        <div class="article-header">
            <h2>Ошибка</h2>
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div>  
    </article>
{% else %}
<article class="form-article">
    <section class="form-section">
        <div class="form-header">
            <h2>{% block header %}Заголовок{% endblock %}</h2>
        </div>
        {% for error in form.errors %}
            <div class="alert" role="alert">
                {{ error }}
            </div>
        {% endfor %}
        <form method="post">
            <div class="form">
                {% csrf_token %}
                {% for field in form %}
                    <div class="input-help">
                        {{ field }}
                        <div class="help">
                            {% if field.help_text %}
                                {{ field.help_text|safe }}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                <div class="submit">
                    {% if '/login/' in request.path %}
                        <a href="{% url 'password_reset' %}">
                            Забыли пароль?
                        </a>
                    {% endif %}
                    <button type="submit">
                        {% block button %}Кнопка{% endblock %}
                    </button>
                </div>
            </div>
        </form>
    </section>
</article>
    {% endif %}
{% endblock %}

dayanik/templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% for post in posts %}
        {% include 'post_item.html' %}
    {% endfor %}
{% endblock %}

dayanik/templates/info.html
{% extends 'base.html' %}
{% block title %}Титулка{% endblock %}
{% block content %}
<article class="article">
    <div class="article-header">
        <h2>{% block header %}Заголовок{% endblock %}</h2>
        <p>{% block paragraph %}Параграф{% endblock %}</p>
    </div>  
</article>
{% endblock %}

dayanik/templates/nav.html
<a href="{% url 'posts:dayanik' %}">Dayanik</a>
<a href="{% url 'posts:index' %}">Блог</a>
{% if user.is_authenticated %}
<a href="{% url 'posts:profile' request.user.username %}">Мой профиль</a>
{% else %}
<a href="{% url 'login' %}">Войти</a>
<a href="{% url 'users:signup' %}">Регистрация</a>
{% endif%}

dayanik/templates/new_post.html
<section class="post-form-section">
    <div class="post-form-header">
        <h2>
            {% if 'edit' in request.path %}
            Редактирование
            {% else %}
            Новая статья
            {% endif %}
        </h2>
    </div>
    {% for error in form.errors %}
        <div class="alert" role="alert">
            {{ error }}
        </div>
    {% endfor %}
    <form method="post">
        <div class="form">
            {% csrf_token %}
            {% for field in form %}
                <div class="input-help">
                    {{ field }}
                    <div class="help">
                        {% if field.help_text %}
                            {{ field.help_text|safe }}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <div class="submit">
                <button type="submit">
                    {% if 'edit' in request.path %}
                    Редактировать
                    {% else %}
                    Опубликовать
                    {% endif %}
                </button>
            </div>
        </div>
    </form>
</section>

dayanik/templates/post.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    {% include 'post_item.html' %}
{% endblock %}

dayanik/templates/post_edit.html
{% extends 'base.html' %}
{% block title %}Редактирование{% endblock %}
{% block content %}
    {% if request.user == profile %}
    {% include 'new_post.html' %}
    {% endif %}
{% endblock %}

dayanik/templates/post_item.html
<article class="article">
    <div class="post-header">
        <h2><a href="{% url 'posts:post' post.pk %}">{{ post.title }}</a></h2>
        <p><a href="{% url 'posts:profile' post.author.username %}">@{{ post.author.username }}</a> {{ post.pub_date }} {% if request.user == post.author %}<a href="{% url 'posts:post_edit' post.pk %}">Редактирование</a>{% endif %}</p>
    </div>
    <p>{{ post.text|linebreaksbr }}</p>
</article>

dayanik/templates/profile.html
{% extends 'base.html' %}
{% block title %}{{ profile.get_full_name }}{% endblock %}
{% block content %}
    <div class="profile">
        <h2>{{ profile.get_full_name }}</h2>
        <p>Кто я: </p>
        <p>Постов: {{ posts.count }}</p>
        {% if request.user == profile %}
        <p><a href="{% url 'password_change' %}">Изменить пароль</a></p>
        <p><a href="{% url 'logout' %}">Выйти</a></p>
        {% endif %}
        <hr>
        <hr>
    </div>
    {% if request.user == profile %}
        {% include 'new_post.html' %}
    {% endif %}
    <div class="post">
    {% for post in posts %}
        {% include 'post_item.html' %}
    {% endfor %}
    </div>
{% endblock %}

dayanik/users/templates/signup.html
{% extends "form.html" %}
{% block title %}Регистрация{% endblock %}
{% block header %}Регистрация{% endblock %}
{% block button %}Зарегистрироваться{% endblock %}